name: Build Tigerbrew packages for leopard_g4e

on:
  issue_comment:
    types: [created]

jobs:
  trigger_leopard_g4e:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/build-leopard_g4e')
    uses: ./.github/workflows/request-build.yml
    secrets: inherit
    with:
      platform_name: leopard_g4e
